---
bibliography: ~/FRibliography/bibtex/FRibliography.bib
---

</br>
</br>

This website is maintained by [Niko Partanen](https://www.slm.uni-hamburg.de/ifuu/personen/niko-partanen.html) and [Michael Rießler](https://www.skandinavistik.uni-freiburg.de/institut/mitarbeiter/riessler/). We have started this page as an open platform for technical documentation as well as a news forum for language documentation and corpus building projects affiliated with the [Freiburg Research Group in Saami Studies](http://saami.uni-freiburg.de/). 

However, since posts related to other projects carried out at institutions elsewhere are also published, our website is not strictly connected to any specific project or institution.

We use the `rmarkdown` package for building the site. The main reason for this is that [R Markdown](http://rmarkdown.rstudio.com/) allows:

* Writing all content in simple RMD text files, which has many advantages
    + Can be read and used as-is outside the website context 
    + Easily compiled into HTML, PDF, ODT, DOC or other formats
    + Easy to embed R (or almost any other) code
* Allows access to bibliographies
* Keeps the website structure extremely simple
* Pretty fast to compile
* And it still looks pretty good!
