---
layout: post
title:  "Fieldwork map"
date:   2015-07-25 23:55:14
tags: [fieldwork, R]
excerpt_separator: <!--more-->
self_contained: yes
---

Doing language documentation with a language like Komi is in many ways different from working with actually non-documented languages. With Komi there is a long research history and collection of data has been ongoing for about 170 years. The data varies and is uneven, but the new data collected now can only be observed and used in connection to the old. In no village can we ever be the first fieldworkers.<!--more-->

The map below shows the fieldwork done within Iźva Komi and some other Komi dialects by different researchers. This is a simple beta-version, which doesn't contain everything. Complete version will be soon exported from our database, and additions are welcome.

It must be mentioned that this map is heavily biased to the work done by West-European scholars. Naturally, native Komi researchers have been working enormously for decades with different Komi varieties. This bias is simply result of situation where data stored in the Western archives is more accessible for us than what is stored in local Russian archives.

```{r echo=F, warning=F, message=F}
library(rgdal)
library(leaflet)
library(maptools)
library(ggmap)

pal <- colorQuantile("YlGn", NULL, n = 5, na.color=NA)

# state_popup <- paste0("<strong>кар / сикт: </strong>", 
#                       komi@data$Location)

# mb_tiles <- "http://a.tiles.mapbox.com/v3/kwalkertcu.l1fc0hab/{z}/{x}/{y}.png"

mb_attribution <- 'Niko Partanen, work funded by Kone Foundation'

kpv_dial <- readShapePoly("~/Documents/Maps/kpv/kpv-dial.shp", proj4string = CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"))

kpv_izva <- readShapePoly("~/Documents/Maps/kpv/kpv-izma-dial.shp", proj4string = CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"))

leaflet() %>%
  addTiles(# urlTemplate = mb_tiles,  
           attribution = mb_attribution) %>%
  addPolygons(data = kpv_dial,
#              fillColor = ~pal(outID), 
              fillOpacity = 0.4, 
              color = "#BDBDC3", 
              weight = 1) %>%
          addPolygons(data = kpv_izva,
#              fillColor = ~pal(outID), 
              fillOpacity = 0.4, 
              color = "#BDBDC3", 
              weight = 1,
              popup = paste("Сёрнисикас:", kpv_izva@data$name)) %>%
          addMarkers(lng = geocode("Нарьян-Мар")$lon, lat = geocode("Нарьян-Мар")$lat, popup = "Izhva Komi Documentation Project, 2015, Funded by Kone Foundation") %>%
          addMarkers(lng = geocode("Ижма")$lon, lat = geocode("Ижма")$lat, popup = "Izhva Komi Documentation Project, 2014, Funded by Kone Foundation") %>%
          addMarkers(lng = geocode("Пожня")$lon, lat = geocode("Пожня")$lat, popup = "Izhva Komi Documentation Project, 2015, Funded by Kone Foundation") %>%
          addMarkers(lng = geocode("Ловозеро")$lon, lat = geocode("Ловозеро")$lat, popup = "Fieldwork in 2009, Kola Saami Documentation Project, Michael Rießler et.al.") %>%
            addMarkers(lng = geocode("Краснощелье")$lon, lat = geocode("Краснощелье")$lat, popup = "Fieldwork in 2009, Kola Saami Documentation Project, Michael Rießler et.al.") %>%
            addMarkers(lng = geocode("Саранпауль")$lon, lat = geocode("Саранпауль")$lat, popup = "Fieldwork in 2011, Personal work of Niko Partanen and Valentina Viktorovna Filippova") %>%
              addMarkers(lng = geocode("Усинск")$lon, lat = geocode("Усинск")$lat, popup = "Fieldwork in 1966, Erik Vászolyi-Vasse and Gennadiy Baraksanov") %>%
         addMarkers(lng = geocode("Петрун, Республика Коми")$lon, lat = geocode("Петрун, Республика Коми")$lat, popup = "Interview Niko Partanen did in 2011 while studying in Syktyvkar.") %>%
           addMarkers(lng = geocode("Мужи")$lon, lat = geocode("Мужи")$lat, popup = "Károly Rédei interviewed Juri Rochev in Syktyvkar at the 70's, the text is publisked in Zyrian Folklore Texts, Akadémiai Kiadó, 1978.")
#           addCircles(data = komi_per,
#                 color = ~pal(per_komi),
#               popup = paste0("<strong>кар / сикт: </strong>", komi_per$Location, "</strong>, комияс: ", sprintf("%.1f %%", 100*komi_per$per_komi)))
```

