---
layout: post
title:  "Welcome to the blog"
date:   2015-05-16 23:55:14
excerpt_separator: <!--more-->
---

While we document the endangered languages of the world there is quite a lot to do. Data quality, data content, connection with the speech communities, managing different audio and video files – this is in many ways extremely difficult job to do. One would assume that the technical solutions which we use would had been designed to make this work as easy as possible. Somehow this does not seem to be the case. Technology is just a tool, our real questions have nothing to do with it. This blog functions mainly as a platform where one can collect notes and tips about how to do different things.

<!--more-->

How often do we update our archived data? I think it is often done maybe every half a year, just because the uploading process is so inconvenient, slow and unreliable. I'm certain this is not intentional. Surely everyone has done their part well and the tools are designed to work in the best possible manner. But something has gone wrong. 

Filling metadata should be so easy that one does it just for joy of keeping things ordered the easiest possible way. Similarly, archiving should be so easy that one just syncs the newest files in the end of the day. Press a button, collect your stuff, tidy your desk – beep – sync done. Repeat every day you do something with your data. 

This should be possible with current technology. We believe this doesn't need to be so difficult. There are better solutions for almost any aspect of our digital data management, and we are going to figure out what those are. 

At times the tools we need do not exist. But then we have to build them. Luckily, programming nowadays has started to remind more and more building with Legos. There are so many packages and modules for all kinds of languages (R, Python, Ruby – whatever one needs) floating around GitHub and other repositories that often 70% of the work is already done. It's just about combining those pieces together in a way that contributes to language documentation workflow.

This site, LangDoc, has been built in order to disseminate our ideas and practices. It is divided into individual blogposts. We also plan having independent daughter sites for specific projects and datasets.
