---
layout: post
title:  "txt2eaf"
date:   2015-06-22 23:55:14
tags: [ELAN]
excerpt_separator: <!--more-->
---

ELAN XML file is the main format in which we store our annotations. In some workflows people take data out from ELAN into Toolbox or other programs, but in principle it should always be written back to the ELAN file as soon as possible. ELAN file is where the typos should be fixed, the annotations split, that's where the raw data connection is. Lots of technical infra is built around ELAN files. But what about the data that is just in text format? Well, we can turn those also into ELAN files!
<!--more-->

Let's say we have some transcription as a simple text file, or maybe as a csv, with column for the text and the translation. In some sense turning that into an ELAN file is an overkill. This is a move from a rather simple file into a relatively complicated XML. 

## Issues

I don't know how to do the tokenization properly with XSL. Well, that is not the main problem in itself, the difficulty comes from generating the numbers correctly.
