---
title: "Getting data from TLA archive"
excerpt_separator: <!--more-->
date: "2015-10-10 14:56:00"
output: pdf_document
author: Niko Partanen
tags:
- archiving
- data
layout: post
---

This is well covered in a reply in TLA tool forum, but it may be difficult to find. And more importantly, it can be difficult to see in its actual context. Very often we want to download corpus data directly to our own computers, and in many cases there is no option for batch download, only selecting node by node. This is very annoying, in some sense even impossible, and at least not reproducible as it is quite easy to miss files. Batch download is really important feature in order to make sure that one is working with the newest corpus version, even though there naturally are many access issues related to it. <!--more--> In principle one could always allow different portions of the data to be download with different rights, i.e. so that there would be more limited, maybe censored and edited or whatever, edition available in batch download for researchers who want to find out if particular dataset is suitable for their purposes.

However, if the corpus is set as freely open, it is very easy to batch download all files (or only metadata), using Arbil. A new version of Arbil just came out and I'm not sure what are the changes there, but this is the basic process:
