---
title: "Rant about CMDI"
author: "Niko Partanen"
date: "2015-12-01 14:56:00"
output: html_document
layout: post
tags:
- archiving
- data
excerpt_separator: <!--more-->
---

I got recently a task in Hamburger Zentrum für Sprachkorpora to make a CMDI profile for our data, which in the future is going to be increasingly language documentation orientated. In order to make sense into CMDI, I started with ELDP-profile, thinking that one is certainly well customized for language documentation needs. We also had several HZSK profiles, but I guess the best way to design it is to take a wide look into what has been done elsewhere as well. <!--more-->

The main issue seems to be that once the CMDI profile is published it is rather difficult to change it. This makes sense, as many other people may have already adopted it, and they have to fit into the same profile without issues or later demands for modifications.

Earlier when I've been working with metadata I've been often thinking that we should find ways to encode all sort of information into those files. We often have very detailed information about the people we've worked with and the recording situations themselves, and as it is not stricktly speaking linguistic data it would make sense to store that into metadata. I've encountered now quite many times the idea that people are mixing up what goes to metadata and what doesn't, and I do understand that maybe some relatively narrow concept of metadata could make things easier.

One aspect of the question is that as the metadata is public, we can't really store very much information into it. From this perspective as well it should contain just the data which is entirely unproblematic to have in online search catalogues, as an example. **So should the metadata files then contain only the information that can be publicly open and could realistically be relevant for finding the data?**.

Yet this doesn't really remove the question where to store that data that is not really metadata, in the most narrow sense of the word, but that doesn't really fit into the transcription files themselves. I remember someone was once joking in a bar how:

> Some people want to store in the metadata how many teeth the speaker had!

**Yes, they certainly do, and that has to be in a machine readable standardized format!** So actually, how do we store the metadata is a rather small and easily definable question. The real issue is how do we store the rest of the data, basically everything that is between metadata and the transcription files? Usually this data is somewhere on the recordings themselves, and of course in the researcher's notebooks.
