---
title: "Post-production in language documentation"
author: "Niko Partanen"
output:
  html_document:
    toc: true
    toc_float: true
excerpt_separator: <!--more-->
bibliography: ~/FRibliography/bibtex/FRibliography.bib
---

### Modern video workflow

Please see the video below, as I think it explains my point better than just a text could.

<iframe width="560" height="315" src="http://www.youtube.com/embed/9bZkp7q19f0?rel=0" frameborder="0" allowfullscreen></iframe>

This is actually a very typical case in language documentation. Already in the technical side of what we are doing *there is so much work*. And there are so many technical issues to which we have no satisfactory solutions. And this is something that should be just background noise! None of this is even scratching the surface, that is, getting into questions about how the video serves the language documentation and description, what are the ethnographic or anthropologic aspects of all this. Louise Ashmore has already discussed the role of video quite thoroughly [-@ashmore2008a], 

### Some ethnographic practices

Lots of ink could be spilled over the question how to make documentation film more ethnographic. However, I've been thinking that there are also some practices in ethnographic film which could benefit us in language documentation. For example, there is something called "ethnographic companion" [@heider2006a, 60], which could be a pamphlet or short text which ties the events in video to the ethnographic literature. Naturally when we have time-aligned transcription files one could refer this companion directly to the recording as well. There would be many benefits in this, mainly that it would make explicit what is in the materials and how do they link together. That is very much work, but it has potential to make language documentation resources much more usable. So ideally the sessions would be tied together by content related cross-references, and also with external references to the literature, of course. 

The main question is whether the references should be done via time codes or reference id's within the files.

### Open issues

- Audio engineering questions
    + Mixing
    + Using multiple microphones
- Archiving questions
    + Should we archive the intermediate files?
    + Is it enough to archive them, or should we also try to understand those files?
        + I think we have to, as we should adjust our workflow within these tools into something that is correctly reflected in the XML structure as well.
- The role of video in language documentation
    + Are we using video as a 

### References
